# Este arquivo informa ao Netlify as configurações do seu projeto.

[build]
  # Diretório onde suas funções serverless estão localizadas.
  functions = "netlify/functions"

# Regra de redirecionamento para garantir que as funções sejam acessíveis.
# O /* no final (splat) captura qualquer nome de função após /api/
# Ex: /api/create-user -> /.netlify/functions/create-user
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Adiciona a configuração para o "bundler" (empacotador) das funções.
[functions]
  node_bundler = "esbuild"
  # Marca a dependência @netlify/neon como externa para que não seja incluída no pacote final.
  # O próprio ambiente do Netlify já a fornecerá durante a execução.
  external_node_modules = ["@netlify/neon"]

